version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
